### ISSUE TITLE
How to train my own dataset?

### ISSUE THREAD

**Issue by Gonnaaa** [creatis-myriad/plug-and-play-reco-regularization#1]
Hi,

I want to know how to run this model to train my own dataset? I would greatly appreciate it if you could provide some relevant steps or explanations.

Looking forword your answers soon.

Best wishes
Gonnaaa

**Comment by sophie-carneiro** [comment]
Hi, 
Sorry for the time. I did not see the message. 
I just improved the git to make the code clean. I hope it is clearer. An example of how to create and use the dataset to train the reconnecting model is available in sources/source_2D/example.py. 3D has not yet been tested since cleaning the code but it will be soon.

Don't hesitate if you have remaining questions. 

Sophie
